# Cloudflare Pages + D1 config
name = "vfirst"
pages_build_output_dir = "./dist"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"                 # ใช้ใน Functions เป็น env.DB
database_name = "vfirst-db"
database_id = "cc1ae6e3-1f16-483e-9db9-5592e026cb47"   # ได้จากคำสั่ง: npx wrangler d1 create vfirst-db
